spring:
  application:
    name: smart-factory-backend

  datasource:
    # Docker Desktop이 띄운 로컬 DB 주소
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true  # 실행되는 SQL의 가독성
    show-sql: true        # 콘솔에 SQL 로그 출력

  main:
    allow-circular-references: true